---
- include_tasks: sles12_rpms.yml
  tags:
    - install
  when: ansible_distribution_major_version == '12'

- include_tasks: sles15_rpms.yml
  tags:
    - install
  when: ansible_distribution_major_version == '15'

- name: create virtualenv and install pip
  pip: virtualenv="{{ pivenv_path }}"
       virtualenv_python=python
       name=pip
       version=18.0
  tags:
    - install
    - upgrade

- name: create virtualenv and install privacyidea
  pip: virtualenv="{{ pivenv_path }}"
       virtualenv_python=python
       name=privacyidea
       version={{ PI_PACKAGE_VERSION }}
  tags:
    - install
    - upgrade

- name: install pymysql-sa
  pip: virtualenv="{{ pivenv_path }}"
       virtualenv_python=python
       name=pymysql-sa
  tags:
    - install